# Generated by Django 4.2 on 2024-05-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[("INITIATED", "INITIATED"), ("PROCESSED", "PROCESSED")],
                default="INITIATED",
                max_length=200,
            ),
        ),
    ]
