# Generated by Django 4.2.3 on 2023-07-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("benefactor", "benefactor"), ("needy", "needy")],
                default="benefactor",
                max_length=100,
            ),
        ),
    ]
